# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blair Neumann's personal blog
email: blairn@outlook.com
telephone: +14254668358
description: > 
  Blair is a full-stack web and cross-platform mobile Technical Program Manager
  and JavaScript/C# developer located in Seattle, WA, USA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.blairneumann.com" # the base hostname & protocol for your site, e.g. http://example.com
github-username:  blairneumann
publisher: Blair Neumann

excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-tagging

# Plugin: jekyll-paginate
paginate: 2
paginate_path: "/blog/page-:num/"

# Plugin: jekyll-tagging
tag_page_layout: tag
tag_page_dir: tag
tag_feed_layout: tag
tag_feed_dir: tag
tag_page_data:
  sitemap: false
tag_feed_data:
  sitemap: false

# Disqus
disqus_sitename: blairneumann

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values: 
      layout: "post"
      comments: true
      is_post: true
  -
    scope:
      path: ""
      type: "pages"
    values: 
      layout: "page"
      is_page: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json